require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReservationDetailsController do

  # This should return the minimal set of attributes required to create a valid
  # ReservationDetail. As you add validations to ReservationDetail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReservationDetailsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reservation_details as @reservation_details" do
      reservation_detail = ReservationDetail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reservation_details).should eq([reservation_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested reservation_detail as @reservation_detail" do
      reservation_detail = ReservationDetail.create! valid_attributes
      get :show, {:id => reservation_detail.to_param}, valid_session
      assigns(:reservation_detail).should eq(reservation_detail)
    end
  end

  describe "GET new" do
    it "assigns a new reservation_detail as @reservation_detail" do
      get :new, {}, valid_session
      assigns(:reservation_detail).should be_a_new(ReservationDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested reservation_detail as @reservation_detail" do
      reservation_detail = ReservationDetail.create! valid_attributes
      get :edit, {:id => reservation_detail.to_param}, valid_session
      assigns(:reservation_detail).should eq(reservation_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReservationDetail" do
        expect {
          post :create, {:reservation_detail => valid_attributes}, valid_session
        }.to change(ReservationDetail, :count).by(1)
      end

      it "assigns a newly created reservation_detail as @reservation_detail" do
        post :create, {:reservation_detail => valid_attributes}, valid_session
        assigns(:reservation_detail).should be_a(ReservationDetail)
        assigns(:reservation_detail).should be_persisted
      end

      it "redirects to the created reservation_detail" do
        post :create, {:reservation_detail => valid_attributes}, valid_session
        response.should redirect_to(ReservationDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reservation_detail as @reservation_detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReservationDetail.any_instance.stub(:save).and_return(false)
        post :create, {:reservation_detail => {}}, valid_session
        assigns(:reservation_detail).should be_a_new(ReservationDetail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReservationDetail.any_instance.stub(:save).and_return(false)
        post :create, {:reservation_detail => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reservation_detail" do
        reservation_detail = ReservationDetail.create! valid_attributes
        # Assuming there are no other reservation_details in the database, this
        # specifies that the ReservationDetail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ReservationDetail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => reservation_detail.to_param, :reservation_detail => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested reservation_detail as @reservation_detail" do
        reservation_detail = ReservationDetail.create! valid_attributes
        put :update, {:id => reservation_detail.to_param, :reservation_detail => valid_attributes}, valid_session
        assigns(:reservation_detail).should eq(reservation_detail)
      end

      it "redirects to the reservation_detail" do
        reservation_detail = ReservationDetail.create! valid_attributes
        put :update, {:id => reservation_detail.to_param, :reservation_detail => valid_attributes}, valid_session
        response.should redirect_to(reservation_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the reservation_detail as @reservation_detail" do
        reservation_detail = ReservationDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReservationDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => reservation_detail.to_param, :reservation_detail => {}}, valid_session
        assigns(:reservation_detail).should eq(reservation_detail)
      end

      it "re-renders the 'edit' template" do
        reservation_detail = ReservationDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReservationDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => reservation_detail.to_param, :reservation_detail => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reservation_detail" do
      reservation_detail = ReservationDetail.create! valid_attributes
      expect {
        delete :destroy, {:id => reservation_detail.to_param}, valid_session
      }.to change(ReservationDetail, :count).by(-1)
    end

    it "redirects to the reservation_details list" do
      reservation_detail = ReservationDetail.create! valid_attributes
      delete :destroy, {:id => reservation_detail.to_param}, valid_session
      response.should redirect_to(reservation_details_url)
    end
  end

end
