require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VesselsController do

  # This should return the minimal set of attributes required to create a valid
  # Vessel. As you add validations to Vessel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VesselsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vessels as @vessels" do
      vessel = Vessel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vessels).should eq([vessel])
    end
  end

  describe "GET show" do
    it "assigns the requested vessel as @vessel" do
      vessel = Vessel.create! valid_attributes
      get :show, {:id => vessel.to_param}, valid_session
      assigns(:vessel).should eq(vessel)
    end
  end

  describe "GET new" do
    it "assigns a new vessel as @vessel" do
      get :new, {}, valid_session
      assigns(:vessel).should be_a_new(Vessel)
    end
  end

  describe "GET edit" do
    it "assigns the requested vessel as @vessel" do
      vessel = Vessel.create! valid_attributes
      get :edit, {:id => vessel.to_param}, valid_session
      assigns(:vessel).should eq(vessel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vessel" do
        expect {
          post :create, {:vessel => valid_attributes}, valid_session
        }.to change(Vessel, :count).by(1)
      end

      it "assigns a newly created vessel as @vessel" do
        post :create, {:vessel => valid_attributes}, valid_session
        assigns(:vessel).should be_a(Vessel)
        assigns(:vessel).should be_persisted
      end

      it "redirects to the created vessel" do
        post :create, {:vessel => valid_attributes}, valid_session
        response.should redirect_to(Vessel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vessel as @vessel" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vessel.any_instance.stub(:save).and_return(false)
        post :create, {:vessel => {}}, valid_session
        assigns(:vessel).should be_a_new(Vessel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vessel.any_instance.stub(:save).and_return(false)
        post :create, {:vessel => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vessel" do
        vessel = Vessel.create! valid_attributes
        # Assuming there are no other vessels in the database, this
        # specifies that the Vessel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vessel.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => vessel.to_param, :vessel => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested vessel as @vessel" do
        vessel = Vessel.create! valid_attributes
        put :update, {:id => vessel.to_param, :vessel => valid_attributes}, valid_session
        assigns(:vessel).should eq(vessel)
      end

      it "redirects to the vessel" do
        vessel = Vessel.create! valid_attributes
        put :update, {:id => vessel.to_param, :vessel => valid_attributes}, valid_session
        response.should redirect_to(vessel)
      end
    end

    describe "with invalid params" do
      it "assigns the vessel as @vessel" do
        vessel = Vessel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vessel.any_instance.stub(:save).and_return(false)
        put :update, {:id => vessel.to_param, :vessel => {}}, valid_session
        assigns(:vessel).should eq(vessel)
      end

      it "re-renders the 'edit' template" do
        vessel = Vessel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vessel.any_instance.stub(:save).and_return(false)
        put :update, {:id => vessel.to_param, :vessel => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vessel" do
      vessel = Vessel.create! valid_attributes
      expect {
        delete :destroy, {:id => vessel.to_param}, valid_session
      }.to change(Vessel, :count).by(-1)
    end

    it "redirects to the vessels list" do
      vessel = Vessel.create! valid_attributes
      delete :destroy, {:id => vessel.to_param}, valid_session
      response.should redirect_to(vessels_url)
    end
  end

end
